#!/bin/sh
#
# @name Gazebo Duckiedrone DD24-B
#
# @type Quadrotor
#
# Basado en 4001_gz_x500 con la geometría del DD24 (motores en ±0.091 m) y los ajustes
# del dron real que importan para OFFBOARD sin radiocontrol.

. ${R}etc/init.d/rc.mc_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=default}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=dd24}

param set-default SIM_GZ_EN 1

param set-default SENS_EN_GPSSIM 1
param set-default SENS_EN_BAROSIM 0
param set-default SENS_EN_MAGSIM 1

param set-default CA_AIRFRAME 0
param set-default CA_ROTOR_COUNT 4

param set-default CA_ROTOR0_PX 0.091
param set-default CA_ROTOR0_PY 0.091
param set-default CA_ROTOR0_KM 0.05

param set-default CA_ROTOR1_PX -0.091
param set-default CA_ROTOR1_PY -0.091
param set-default CA_ROTOR1_KM 0.05

param set-default CA_ROTOR2_PX 0.091
param set-default CA_ROTOR2_PY -0.091
param set-default CA_ROTOR2_KM -0.05

param set-default CA_ROTOR3_PX -0.091
param set-default CA_ROTOR3_PY 0.091
param set-default CA_ROTOR3_KM -0.05

param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_FUNC2 102
param set-default SIM_GZ_EC_FUNC3 103
param set-default SIM_GZ_EC_FUNC4 104

param set-default SIM_GZ_EC_MIN1 150
param set-default SIM_GZ_EC_MIN2 150
param set-default SIM_GZ_EC_MIN3 150
param set-default SIM_GZ_EC_MIN4 150

param set-default SIM_GZ_EC_MAX1 2400
param set-default SIM_GZ_EC_MAX2 2400
param set-default SIM_GZ_EC_MAX3 2400
param set-default SIM_GZ_EC_MAX4 2400

param set-default MPC_THR_HOVER 0.55
# masa 1.76 kg: en el dron real el empuje de hover medido fue ~0.52

# Como el dron real: se vuela por MAVLink desde la Pi, sin radiocontrol
param set-default COM_RC_IN_MODE 4
param set-default COM_RCL_EXCEPT 4
param set-default NAV_DLL_ACT 0
param set-default COM_OF_LOSS_T 1.0

# Batería simulada: que no baje de 80 % (hover_test pide al menos 50 % para despegar)
param set-default SIM_BAT_MIN_PCT 80
